---
abstract: 'Converts Perl Pod documentation to object tree, contains podlint and podchecker2'
author:
  - 'Marek Rouchal <marekr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Compiler
no_index:
  directory:
    - t
    - inc
requires:
  Pod::Parser: 1.12
  Storable: 0
  Test::Simple: 0.44
  Tree::DAG_Node: 1
version: 0.21
